version: '3.8'
services:
  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: linuxeur
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 90:80

volumes:
  db:
